# Generated by Django 4.0.6 on 2022-07-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('pwd', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('rdate', models.DateTimeField()),
                ('udate', models.DateTimeField()),
            ],
        ),
    ]
